spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: Employee-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9100


management:
  endpoints:
    web:
      exposure:
        include: "*"


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
