server:
  port: 9100

spring:
  application:
    name: Employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: SatyamN.26.
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
